config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  get "home/about" => "homes#about"
  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end
  devise_for :users
  resources :books, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update, :delete]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum:200}


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_one_attached :profile_image

  validates :name, uniqueness: true, length: {in:2..20}
  validates :introduction, length: {maximum:50}

  def get_profile_image(width,height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :is_matching_login_user, only: [:edit, :update]

  
  def index
    @user = User.find(current_user.id)
    @book_new = Book.new
    @books = Book.all
  end
  
  def create
    @book_new = Book.new(book_params)
    @book_new.user_id = current_user.id
    if @book_new.save
      flash[:notice] ="You have created book successfully."
      redirect_to book_path(@book_new.id)
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end
    
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    book = Book.find(params[:id])
    user = book.user
    unless user.id == current_user.id
      redirect_to books_path
    end
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
    
  end
  
  def about
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_matching_login_user, only: [:edit, :update]

  def index
    @user = User.find(current_user.id)
    @book_new = Book.new
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book_new = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <div class="user_info">
        <h2>User info</h2>
        <%= image_tag user.get_profile_image(100,100)%>
        <table class="table">
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction%></th>
          </tr>
        </table>
        <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block" do%>
          <i class="fa-solid fa-user-gear"></i>
        <% end %>
      </div>
      <div class="new_book">
        <h2>New book</h2>
        <%= form_with model: book_new do |f| %>
          <p>Title</p>
            <%= f.text_field :title %>
          <p>Opinion</p>
            <%= f.text_area :body %>
            <%= f.submit 'Create Book', class:"btn btn-success" %>
        <% end %>
      </div>
    </div>

app/views/books/edit.html.erb
<div class="container">
  <h1>Editing Book</h1>
  
    <% if @book.errors.any? %>
    <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
    <% end %>

  <%= form_with model: @book do |f| %>

    <p>Title</p>
    <%= f.text_field :title %>

    <p>Opinion</p>
    <%= f.text_area :body %>

  <div class="actions">
    <%= f.submit 'Update Book', class:"btn btn-success"%>
  </div>
  <% end %>
  
  <%= link_to "Show", book_path(@book.id) %>
  |
  <%= link_to "Back", books_path%>
</div>

app/views/books/index.html.erb
  <div class=" col-10 mx-auto">
    <% if @book_new.errors.any? %>
      <h3><%= pluralize(@book_new.errors.count, "error") %> prohibited this obj from being saved:</h3>
      <ul>
        <% @book_new.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <%= render 'new', user: @user, book_new: @book_new %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(80,80)%>
              <% end %>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
                <%= book.title%>
              <% end %>
            </td>
            <td><%= book.body%></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<%= render 'new', user: @user, book_new: @book_new%>


    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= image_tag @user.get_profile_image(80,80)%>
                <p><%= @user.name %></p>
              <% end %>
            <td>
              <%= link_to book_path(@book.id) do %>
                <%= @book.title %>
              <% end %>
            </td>
            <td><%= @book.body%></td>
            <% if @user == current_user %>
            <td>
              <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success"%>
            </td>
            <td>
              <%= link_to "Destroy", book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？",
                  class:"btn btn-danger"%>
            </td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <div class= "mx-auto ">
      <h1>
        Welcome to <strong><i class="fa-solid fa-book"></i>Bookers</strong>!!
      </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class= "mx-auto">
      <h1>
        welcome to <strong><i class="fa-solid fa-book"></i>Bookers</strong>!!
      </h1>
      <p>
        In <strong><i class="fa-solid fa-book"></i>Bookers</strong>,<br>
        you can share and exchange your opinions ,inpressions ,and emotions<br>
        about various books!
      </p>

      <%= link_to "Log in", new_user_session_path, class:"btn btn-info mx-auto col-11 mb-3" %>

      <%= link_to "Sign up", new_user_registration_path, class:"btn btn-success mx-auto col-11" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/ac7cef6f2b.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <nav class="navbar navbar-dark bg-dark">
      <div class="container">
        <div class="navbar-brand">
          <%= link_to "Bookers", "/", class: 'nav-link text-light' %>
        </div>
        <button class="navbar-toggler" type="button"
          data-toggle="collapse"
          data-target="#navbarNavDropdown"
          aria-controls="navbarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-house"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-users"></i> Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-book-open"></i> Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-right-from-bracket"></i> Log out
                <% end %>
              </li>
            <% else %>
            <li class="nav-item">
                <%= link_to "/", class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-house"></i> Home
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to "/home/about", class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-link"></i> About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  new_user_registration_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to  new_user_session_path, class: 'nav-link text-light' do %>
                  <i class="fa-solid fa-right-to-bracket"></i> Log in
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>
    <main>
      <% flash.each do |message_type, message| %>
       <%= content_tag :div, message, class: message_type %>  
      <% end %>
      <%= yield %>
    </main>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container">
  <h1>User info</h1>
  
  <% if @user.errors.any? %>
    <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  <% end %>

  <%= form_with model: @user do |f| %>

    <p>Name</p>
    <%= f.text_field :name %>

    <p>Image</p>
    <%= f.file_field :profile_image, accept: "image/*" %>

    <p>Introduction</p>
    <%= f.text_area :introduction %>

  <div class="actions">
    <%= f.submit 'Update User', class:"btn btn-secondary " %>
  </div>
  <% end %>
</div>

app/views/users/index.html.erb
<%= render 'books/new', user: @user, book_new: @book_new%>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th></th>
      </tr>
      </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.get_profile_image(80,80)%>
        </td>
        <td>
          <%= user.name %>
        </td>
        <td><%= link_to "Show", user_path(user.id)%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/show.html.erb
<%= render '/books/new', user: @user, book_new: @book_new%>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(@user.id) do %>
            <%= image_tag @user.get_profile_image(80,80)%>
          <% end %>
        <td>
          <%= link_to book_path(book.id) do %>
          <%= book.title %>
          <% end %>
         </td>
        <td><%= book.body%></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>